version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pingpongdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pingpongdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pingpongdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: devpass
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: